---
title: "RQ3"
format: 
  html:
    embed-resources: true
    fig-width: 8
    fig-height: 8
    code-link: true
    code-fold: true
    code-tools: true
    df-print: paged
    toc: true
    grid:
      body-width: 900px
editor: source
---

# Load data

We could stratify the data by whether they have participated recently?

```{r}
#| output: false
source("0_load_data.R")
```

# Original Sample Size 

```{r}
nrow(df0)
df0 %>%
  pull(randomfamid) %>%
  unique() %>%
  length()
```


# Participation Rates by Sex and Zygosity (All Time Points)

```{r}

# Create a comprehensive table showing participation rates by sexzyg for all time points
df %>%
  filter(twin == 1) %>%
  select(sexzyg, all_of(paste0(rq1y_twin,"1"))) %>%
  pivot_longer(
    cols = -sexzyg,
    names_to = "variable",
    values_to = "participation"
  ) %>%
  mutate(
    twin = ifelse(str_detect(variable, "1$"), "twin1", "twin2"),
    timepoint = var_to_label(variable),
    timepoint = factor(timepoint, levels = var_to_label(rq1y_twin1))
  ) %>%
  group_by(timepoint, sexzyg) %>%
  summarise(
    n = sum(!is.na(participation)),
    participation_rate = mean(participation, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(timepoint) %>%
  gt() %>%
  gt::fmt_percent(participation_rate, decimals = 1)
  


```

# Correlations between twins over time 

```{r}

  calc_twin_correlations <- function(data, vars) {
    results <- map_dfr(vars, ~ {
      twin1_var <- paste0(.x, "1")
      twin2_var <- paste0(.x, "2")
      tibble(
        timepoint = .x,
        correlation = cor(data[[twin1_var]], data[[twin2_var]], use = "pairwise.complete.obs")
      )
    })
    return(results)
  }

  df %>%
    filter(random == 1) %>%
    group_by(sexzyg) %>%
    group_modify(~ calc_twin_correlations(.x, rq1y_twin)) %>%
    mutate(timepoint_label = var_to_label(paste0(timepoint,"1"), twinsuffix = FALSE)) %>%
    select(sexzyg, timepoint_label, correlation) %>%
    pivot_wider(
      names_from = sexzyg,
      values_from = correlation
    ) %>%
    knitr::kable(
      caption = "Twin Correlations by Sex/Zygosity Group Across Time Points",
      digits = 3
    )

```

# ACE estimates

```{r}

sapply(rq1y_twin, function(x) calc_ace_binary(data = df, var = x)) %>%
  t() %>%
  data.frame() %>%
  rownames_to_column(var = "timepoint") %>%
  mutate(
    timepoint = var_to_label(paste0(timepoint,"1"))
  ) %>%
  knitr::kable(
    digits = 2
  )

```

